disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - force_cast
 - identifier_name
 - function_body_length
 - line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods
